# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\"\x1b\n\x08QueryReq\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1d\n\tQueryResp\x12\x10\n\x08response\x18\x01 \x01(\t2*\n\x03LLM\x12#\n\x08QueryLLM\x12\t.QueryReq\x1a\n.QueryResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQ']._serialized_start=13
  _globals['_QUERYREQ']._serialized_end=40
  _globals['_QUERYRESP']._serialized_start=42
  _globals['_QUERYRESP']._serialized_end=71
  _globals['_LLM']._serialized_start=73
  _globals['_LLM']._serialized_end=115
# @@protoc_insertion_point(module_scope)
