name: Python CI/CL

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install black flake8 codespell

      # Run Black to check Python formatting
      - name: Run black
        run: |
          black --check .

      # Run flake8 to lint Python code
      - name: Run flake8
        run: |
          flake8 .

      # Run codespell to check for spelling errors
      - name: Run codespell
        run: |
          codespell

      # Auto-fix formatting with black if there are issues
      - name: Auto-fix formatting with black
        if: failure() # Run only if the formatting check fails
        run: |
          black .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Auto-format code with black" || echo "No changes to commit"
          git push
